### PR TITLE
Version 7.

### PR DESCRIPTION
**Pull request by stephane-13**
Allow to select the target monitor type (primary, secondary, all) for the dimming effect.

### CODE REVIEW

**Comment by mausmalone** [comment]
Hey Stephane - I really love this extension - but is there any way I could make a request? Would it be possible to have a setting that ignores any windows that are Always on Top? (Meta.window.is_above()) I was going to try to do this myself and honestly while I think the coding would be fairly easy I just can't wrap my head around how GitHub works. Anyhow, I was thinking this feature would be a real improvement for Firefox's picture-in-picture video or Lollypop's mini player.

**Comment by stephane-13** [comment]
Yes, that should definitely be possible and rather easy to implement, as long as the is_above() function does what it should do. Which is not particularly clear when looking at the doc here: https://gjs-docs.gnome.org/meta13~13/meta.window#method-is_above
But anyway, I will test that :smile:

**Comment by stephane-13** [comment]
I've added the option to disable / enable the dimming effect for windows marked as always on top in this PR.
It will be part of the next release, but you can already test the extension by downloading and manually installing the zip file included in branch v7:
https://github.com/stephane-13/gnome-shell-extension-dim-background-windows/blob/v7/dim-background-windows%40stephane-13.github.com.shell-extension.zip

**Comment by mausmalone** [comment]
Awesome! I downloaded the zip and I can tell you that it's working perfectly for me in Ubuntu 23.04!

**Comment by stephane-13** [comment]
Thank you for the confirmation :smile: 
The new version of the extension has been submitted for review on https://extensions.gnome.org.

**Pull request merged**
